---
resources:
- name: werty
  type: time
  source: 
    interval: 15m
    start: 4:00 PM
    stop: 5:00 PM
    location: America/New_York

jobs:
- name: almost-dutch
  plan:
  - get: werty
    trigger: true
#   - task: hello
#     config:
#       platform: linux
#       run:
#         path: hello
